INSERT INTO `pool_quest` VALUES (14074, 34880, 'Tournament - Champion - The Silver Covenant - Sea - A Leg Up');
INSERT INTO `pool_quest` VALUES (14152, 34880, 'Tournament - Champion - The Silver Covenant - Sea - Rescue At Sea');
INSERT INTO `pool_quest` VALUES (14077, 34880, 'Tournament - Champion - The Silver Covenant - Sea - The Lights Mercy');
INSERT INTO `pool_quest` VALUES (14080, 34880, 'Tournament - Champion - The Silver Covenant - Sea - Stop the Aggression');
INSERT INTO `pool_quest` VALUES (14143, 34771, 'Tournament - Champion - The Sunreavers - Sea - A Leg Up');
INSERT INTO `pool_quest` VALUES (14136, 34771, 'Tournament - Champion - The Sunreavers - Sea - Rescue At Sea');
INSERT INTO `pool_quest` VALUES (14144, 34771, 'Tournament - Champion - The Sunreavers - Sea - The Lights Mercy');
INSERT INTO `pool_quest` VALUES (14140, 34771, 'Tournament - Champion - The Sunreavers - Sea - Stop the Aggression');
INSERT INTO `pool_quest` VALUES (14092, 34912, 'Tournament - Champion - The Silver Covenant - Tournament - Breakfast Of Champions');
INSERT INTO `pool_quest` VALUES (14141, 34912, 'Tournament - Champion - The Silver Covenant - Tournament - Gormok Wants His Snobolds');
INSERT INTO `pool_quest` VALUES (14145, 34912, 'Tournament - Champion - The Silver Covenant - Tournament - What Do You Feed a Yeti, Anyway?');
INSERT INTO `pool_quest` VALUES (14076, 34914, 'Tournament - Champion - The Sunreavers - Tournament - Breakfast Of Champions');
INSERT INTO `pool_quest` VALUES (14090, 34914, 'Tournament - Champion - The Sunreavers - Tournament - Gormok Wants His Snobolds');
INSERT INTO `pool_quest` VALUES (14112, 34914, 'Tournament - Champion - The Sunreavers - Tournament - What Do You Feed a Yeti, Anyway?');
INSERT INTO `pool_quest` VALUES (14101, 34882, 'Tournament - Champion - The Argent Crusade - Defeat - Drottinn Hrothgar');
INSERT INTO `pool_quest` VALUES (14102, 34882, 'Tournament - Champion - The Argent Crusade - Defeat - Mistcaller Yngvar');
INSERT INTO `pool_quest` VALUES (14104, 34882, 'Tournament - Champion - The Argent Crusade - Defeat - Ornolf The Scarred');
INSERT INTO `pool_quest` VALUES (14105, 34882, 'Tournament - Champion - The Argent Crusade - Defeat - Deathspeaker Kharos');
INSERT INTO `pool_quest` VALUES (14107, 35094, 'Tournament - Champion - The Argent Crusade - Kraken - The Fate Of The Fallen');
INSERT INTO `pool_quest` VALUES (14108, 35094, 'Tournament - Champion - The Argent Crusade - Kraken - Get Kraken!');
